=== robbyn/gianadda/src/org/tastefuljava/gianadda/catalog/jedo.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT mapping (class*)>
<!ATTLIST mapping package CDATA #IMPLIED>

<!ELEMENT class (id?,(property|component|reference|collection)*,
        load?,query*,insert?,update?,delete?,statement*)>
<!ATTLIST class name CDATA #REQUIRED>

<!ELEMENT id (property+)>

<!ELEMENT property EMPTY>
<!ATTLIST property
    name CDATA #REQUIRED
    column CDATA #IMPLIED
>

<!ELEMENT component (property+)>
<!ATTLIST component name CDATA #REQUIRED>

<!ELEMENT reference EMPTY>
<!ATTLIST reference
    name CDATA #REQUIRED
    column CDATA #REQUIRED
    fetch-mode (eager|lazy) #IMPLIED
>

<!ELEMENT collection EMPTY>
<!ATTLIST collection
    name CDATA #REQUIRED
    query CDATA #REQUIRED
    fetch-mode (eager|lazy) #IMPLIED
>

<!ELEMENT load (#PCDATA)>

<!ELEMENT query (#PCDATA)>
<!ATTLIST query
    name CDATA #REQUIRED
    parameters CDATA #IMPLIED
>

<!ELEMENT insert (#PCDATA)>
<!ATTLIST insert get-generated-keys (true|false) #IMPLIED>

<!ELEMENT update (#PCDATA)>

<!ELEMENT delete (#PCDATA)>

<!ELEMENT statement (#PCDATA)>
<!ATTLIST statement
    name CDATA #REQUIRED
    parameters CDATA #IMPLIED
>

=== robbyn/gianadda/src/org/tastefuljava/gianadda/catalog/mapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapping PUBLIC '-//tastefuljava.org//Jedo Mapping File 1.0//EN' 'jedo.dtd'>
<mapping package="org.tastefuljava.gianadda.domain">
    <class name="Folder">
        <id>
            <property name="id" column="ID"/>
        </id>
        <property name="parentId" column="PARENT_ID"/>
        <property name="name" column="NAME"/>
        <property name="title" column="TITLE"/>
        <property name="description" column="DESCRIPTION"/>

        <load>
            SELECT * FROM folders
            WHERE ID=${id}
        </load>
        <query name="root" parameters="name">
            SELECT * FROM folders
            WHERE PARENT_ID IS NULL AND NAME=${name}
        </query>
        <query name="subfolder" parameters="parent,name">
            SELECT * FROM folders
            WHERE PARENT_ID=${parent.id} AND NAME=${name}
        </query>
        <query name="subfolders" parameters="parent">
            SELECT * FROM folders
            WHERE PARENT_ID=${parent.id}
        </query>
        <insert get-generated-keys="true">
            INSERT INTO folders(PARENT_ID,NAME,TITLE,DESCRIPTION)
            VALUES(${parent.id},${name},${title},${description});
        </insert>
        <update>
            UPDATE folders
            SET PARENT_ID=${parent.id},NAME=${name},TITLE=${title},
                DESCRIPTION=${description},
            WHERE ID=${id}
        </update>
        <delete>
            DELETE FROM folders WHERE ID=${id}
        </delete>
    </class>

    <class name="Picture">
        <id>
            <property name="id" column="ID"/>
        </id>
        <property name="folderId" column="FOLDER_ID"/>
        <property name="name" column="NAME"/>
        <property name="dateTime" column="DATETIME"/>
        <property name="width" column="WIDTH"/>
        <property name="height" column="HEIGHT"/>
        <property name="description" column="DESCRIPTION"/>
        <property name="artist" column="ARTIST"/>
        <property name="copyright" column="COPYRIGHT"/>
        <component name="gpsData">
            <property name="latitude" column="LATITUDE"/>
            <property name="longitude" column="LONGITUDE"/>
            <property name="altitude" column="ALTITUDE"/>
        </component>

        <load>
            SELECT * FROM pictures
            WHERE ID=${id}
        </load>
        <query name="byName" parameters="folder,name">
            SELECT * FROM pictures
            WHERE FOLDER_ID=${folder.id} AND NAME=${name}
        </query>
        <query name="inFolder" parameters="folder">
            SELECT * FROM pictures
            WHERE FOLDER_ID=${folder.id}
        </query>
        <insert get-generated-keys="true">
            INSERT INTO pictures(FOLDER_ID,NAME,DATETIME,WIDTH,HEIGHT,LATITUDE,
                LONGITUDE,ALTITUDE,DESCRIPTION,ARTIST,COPYRIGHT)
            VALUES(${folder.id},${name},${dateTime},${width},${height},
                ${gpsData.latitude},${gpsData.longitude},${gpsData.altitude},
                ${description},${artist},${copyright});
        </insert>
        <update>
            UPDATE pictures
            SET FOLDER_ID=${folder.id},NAME=${name},DATETIME=${dateTime},
                WIDTH=${width},HEIGHT=${height},LATITUDE=${gpsData.latitude},
                LONGITUDE=${gpsData.longitude},ALTITUDE=${gpsData.altitude},
                DESCRIPTION=${description},ARTIST=${artist},
                COPYRIGHT=${copyright}
            WHERE ID=${id}
        </update>
        <delete>
            DELETE FROM pictures WHERE ID=${id}
        </delete>
    </class>
</mapping>
